networks:
  kafka-net:
    external: true 
  sonar-net:
    external: true

services:
  orchestrate:
    image: leeyumin/orchestrate:v250826
    container_name: orchestrate
    environment:
      KAFKA_SERVER: kafka:9092
    networks: 
      - kafka-net

  translate:
    image: leeyumin/translate:v250826.c
    container_name: translate
    environment:
      KAFKA_SERVER: kafka:9092
      AUTO_OFFSET_RESET: earliest
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - "/home/ubuntu/vectordb/eGovCodeDB_0805:/vectordb/eGovCodeDB_0805"
    networks: 
      - kafka-net

  chatbot:
    image: leeyumin/chatbot:v250826.a
    container_name: chatbot
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 8000:8000

  security:
    image: leeyumin/security:v250826
    container_name: security
    environment:
      KAFKA_SERVER: kafka:9092
      AUTO_OFFSET_RESET: earliest
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SONAR_URL: http://sonarqube:9000
      SONAR_TOKEN: ${SONAR_TOKEN}
      CHROMA_QUERY_TIMEOUT: 8
      RAG_FORCE_PEEK: 0
    networks: 
      - kafka-net
      - sonar-net